before:
  hooks:
    - go mod tidy

builds:
  - main: "."
    binary: kubesec
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/controlplaneio/kubesec/v2/cmd.version={{.Version}}
      - -X github.com/controlplaneio/kubesec/v2/cmd.commit={{.FullCommit}}
      - -X github.com/controlplaneio/kubesec/v2/cmd.date={{.CommitDate}}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  name_template: "{{ .Tag }}-next"
