---
name: Linting - YAML
permissions: {}
# Split until path filtering for jobs added
# https://github.community/t/path-filtering-for-jobs-and-steps/16447
on:
  push:
    branches: [master]
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches: [master]
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1
