---
name: Linting - Dockerfile
permissions: {}
# Split until path filtering for jobs added
# https://github.community/t/path-filtering-for-jobs-and-steps/16447
on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"
  pull_request:
    branches: [master]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run hadolint
        uses: reviewdog/action-hadolint@921946a7ebaaf08ac72607bad67209f4e52b5407 # v1
