---
name: Linting - Dockerfile
permissions: {}
# Split until path filtering for jobs added
# https://github.community/t/path-filtering-for-jobs-and-steps/16447
on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"
  pull_request:
    branches: [master]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run hadolint
        uses: reviewdog/action-hadolint@1b2cfa6ba72072ad35158d7ff3aa49bbdc03506d # v1
