---
name: Linting - YAML
# Split until path filtering for jobs added
# https://github.community/t/path-filtering-for-jobs-and-steps/16447
on:
  push:
    branches: [master]
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches: [master]
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1.6
